version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/Users/joasierr/Downloads/jenkins_home:/var/jenkins_home"
    restart: always